### ISSUE TITLE
Drag and drop item

### ISSUE THREAD

**Issue by Dame-du-Lac** [admiralnlson/castle-falkenstein-fvtt#9]
Drag and drop Item doesn't function anymore on Actor sheets

**Comment by admiralnlson** [comment]
As discussed in the FR Discord,
https://discord.com/channels/715943353409339425/718749225847881789/1120251610770178088

This is a regression which I'm not sure comes from a change in Core or a mistake on my side.

It's still possible to achieve this by dropping the item on another item already present in the list, or on the title bar if the list is currently empty.

This is obviously less than ideal of course.

I'll keep this issue open for now, and see if I can restore the old behaviour which was more natural.
